mcu.iosync.MCU:
    enable: IOHUB_BOOL
    name:
        IOHUB_STRING:
            min_length: 1
            max_length: 32
            first_char_alpha: True    
    model_name:
        IOHUB_STRING:
            min_length: 0
            max_length: 32
    manufacturer_name: 
        IOHUB_STRING:
            min_length: 0
            max_length: 32
    serial_number:
        IOHUB_STRING:
            min_length: 1
            max_length: 32
    serial_port:
        IOHUB_STRING:
            min_length: 1
            max_length: 32
    time_sync_interval:
            IOHUB_FLOAT:
                min: 0.05
                max: 5.0
    device_timer:
        interval:
            IOHUB_FLOAT:
                min: 0.001
                max: 0.500
    save_events: IOHUB_BOOL
    stream_events: IOHUB_BOOL
    auto_report_events: False    
    monitor_event_types:
        IOHUB_LIST:
            valid_values: [ AnalogInputEvent, DigitalInputEvent, ThresholdEvent]
            min_length: 0
            max_length: 3
    event_buffer_length:
        IOHUB_INT:
            min: 1
            max: 2048    
    device_number: 0
    model_number:
        IOHUB_STRING:
            min_length: 1
            max_length: 16
    manufacture_date: IOHUB_DATE
    software_version:
        IOHUB_STRING:
            min_length: 1
            max_length: 8    
    hardware_version: 
        IOHUB_STRING:
            min_length: 1
            max_length: 8
    firmware_version: 
        IOHUB_STRING:
            min_length: 1
            max_length: 8
