eyetracker.hw.gazepoint.gp3.EyeTracker:
    name: 
        IOHUB_STRING:
            min_length: 1
            max_length: 32
            first_char_alpha: True
    enable: IOHUB_BOOL
    model_name: GP3
    serial_number:
        IOHUB_STRING:
            min_length: 0
            max_length: 32
    manufacturer_name: GazePoint
    save_events: IOHUB_BOOL
    stream_events: IOHUB_BOOL
    auto_report_events: False
    event_buffer_length: 
        IOHUB_INT:
            min: 1
            max: 2048
    monitor_event_types:           
        IOHUB_LIST:
            valid_values: [BinocularEyeSampleEvent, FixationStartEvent, FixationEndEvent]
            min_length: 0
            max_length: 3
    runtime_settings:
        sampling_rate: 60
        track_eyes: [BINOCULAR,]
    calibration:
        target_duration:
            IOHUB_FLOAT:
                min: 0.25
                max: 2.5
        target_delay: 
            IOHUB_FLOAT:
                min: 0.25
                max: 2.5
    device_number: 0
    manufacture_date: IOHUB_DATE
    model_number:
        IOHUB_STRING:
            min_length: 1
            max_length: 16
    software_version:
        IOHUB_STRING:
            min_length: 1
            max_length: 8    
    hardware_version: 
        IOHUB_STRING:
            min_length: 1
            max_length: 8
    firmware_version: 
        IOHUB_STRING:
            min_length: 1
            max_length: 8