# experiment_config.yaml: settings related to the experiment being run when the run.py script is launched,
# any custom session variables you want displayed in a dialog for input at the start of the experiment

title: selectTrackerTest
code: selectTR
version: '1.0'
description: User looks at an image and program counts fixations and dwell times.
session_defaults:
    name: Session Name
    code: E1S01
    comments: None
    user_variables:
        participant_age: Unknown
        eye_color: Unknown
session_variable_order: [ name, code, comments, participant_age, eye_color ]
event_buffer_length: 2048
process_affinity: []
remaining_processes_affinity: []
ioHub:
    enable: True
    process_affinity: []
    config: iohub_config.yaml

  
