monitor_devices:
    - Display:
        name: display
        reporting_unit_type: pix
        device_number: 0
        physical_dimensions:
            width: 590
            height: 340
            unit_type: mm
        default_eye_distance:
            surface_center: 500
            unit_type: mm
        psychopy_monitor_name: default

    - Keyboard:
        name: keyboard

    - Mouse:
        name: mouse

    - Experiment:
        name: experimentRuntime

# Gazepoint GP3 Config (uncomment below device config to use)
    - eyetracker.hw.gazepoint.gp3.EyeTracker:
        enable: True
    
        # The variable name of the device that will be used to access the ioHub Device class
        # during experiment run-time, via the devices.[name] attribute of the ioHub
        # connection or experiment runtime class.
        name: tracker
    
        # Should eye tracker events be saved to the ioHub DataStore file when the device
        # is recording data ?
        save_events: True
    
        # Should eye tracker events be sent to the Experiment process when the device
        # is recording data ?
        stream_events: True
    
        # How many eye events (including samples) should be saved in the ioHub event buffer before
        # old eye events start being replaced by new events. When the event buffer reaches
        # the maximum event length of the buffer defined here, older events will start to be dropped.
        event_buffer_length: 1024
    
        # The GP3 implementation of the common eye tracker interface supports the
        # BinocularEyeSampleEvent event type.
        monitor_event_types: [ BinocularEyeSampleEvent, FixationStartEvent, FixationEndEvent]
    
        device_timer:
            interval: 0.005
    
        calibration:        
            # target_duration is the number of sec.msec that a calibration point should
            # be displayed before moving onto the next point.
            # (Sets the GP3 CALIBRATE_TIMEOUT)
            target_duration: 1.25
            # target_delay specifies the target animation duration in sec.msec.
            # (Sets the GP3 CALIBRATE_DELAY)
            target_delay: 0.5

# SRR EyeLink Config (uncomment below device config to use)
#    - eyetracker.hw.sr_research.eyelink.EyeTracker:
#        name: tracker
#        save_events: True
#        stream_events: True
#        device_timer:
#            interval: 0.001
#        monitor_event_types: [ MonocularEyeSampleEvent, BinocularEyeSampleEvent, FixationStartEvent, FixationEndEvent, SaccadeStartEvent, SaccadeEndEvent, BlinkStartEvent, BlinkEndEvent]
#        simulation_mode: False
#        enable_interface_without_connection: False
#        network_settings: 100.1.1.1
#        default_native_data_file_name: et_data
#        runtime_settings:
#            sampling_rate: 1000
#            track_eyes: RIGHT_EYE
#            sample_filtering:
#                FILTER_ONLINE: FILTER_OFF
#            vog_settings:
#                pupil_measure_types: PUPIL_AREA
#                tracking_mode: PUPIL_CR_TRACKING
#                pupil_center_algorithm: CENTROID_FIT
#        calibration:
#            type: NINE_POINTS
#            auto_pace: True
#            pacing_speed: 1.5
#            screen_background_color: [128,128,128]
#            target_type: CIRCLE_TARGET
#            target_attributes:
#                outer_diameter: 33
#                inner_diameter: 6
#                outer_color: [255,255,255]
#                inner_color: [0,0,0]
#        model_name: EYELINK 1000 TOWER

# Tobii Config (uncomment below device config to use)
#    - eyetracker.hw.tobii.EyeTracker:
#        enable: True
#        name: tracker
#
#        # The model name of the Tobii device that you wish to connect to
#        # can be specified here, and only Tobii systems matching that model
#        # name will be considered as possible candidates for connection.
#        # If you only have one Tobii system connected to the computer,
#        # this field can just be left empty.
#        model_name:
#
#        # The serial number of the Tobii device that you wish to connect to.
#        # If set, only the Tobii system matching that serial number will be
#        # connected to if found.
#        # If you only have one Tobii system connected to the computer,
#        # this field can just be left empty.
#        serial_number:
#
#        calibration:
#            # THREE_POINTS,FIVE_POINTS,NINE_POINTS
#            type: FIVE_POINTS
#
#            # Should the target positions be randomized?
#            randomize: True
#
#            # auto_pace can be True or False. If True, the eye tracker will 
#            # automatically progress from one calibration point to the next.
#            # If False, a manual key or button press is needed to progress to
#            # the next point.
#            auto_pace: True
#            
#            # pacing_speed: the number of sec.msec that a calibration point
#            # should be displayed before moving onto the next point. Only
#            # used when auto_pace is set to True.
#            pacing_speed: 1.5
#            
#            # screen_background_color specifies the r,g,b background color to 
#            # set the calibration, validation, etc, screens to.
#            # Each element of the color should be a value between 0 and 255.
#            screen_background_color: [128,128,128]
#            
#            # The associated target attribute properties can be supplied
#            # for the fixation target used during calibration.
#            # Sizes are in pixels, colors in rgb255 format:
#            target_attributes:
#                 outer_diameter: 35
#                 outer_stroke_width: 2
#                 outer_fill_color: [128,128,128]
#                 outer_line_color: [255,255,255]
#                 inner_diameter: 7
#                 inner_stroke_width: 1
#                 inner_color: [0,0,0]
#                 inner_fill_color: [0,0,0]
#                 inner_line_color: [0,0,0]
#                 animate:
#                     enable: True
#                     movement_velocity: 750.0  # 750 pix / sec
#                     expansion_ratio: 3.0  # expands to 3 x the starting size
#                     expansion_speed: 45.0  # exapands at 45.0 pix / sec
#                     contract_only: True        
#        runtime_settings:
#            sampling_rate: 60

data_store:
    enable: True

